[theme]
primaryColor = "#4B6CC1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FB"
textColor = "#1F2937"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
enableCORS = false

[client]
toolbarMode = "minimal"
[theme]
primaryColor = "#4B6CC1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FB"
textColor = "#1F2937"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
enableCORS = false

[client]
toolbarMode = "minimal"

